
package defence_system;

import javax.swing.JOptionPane;

/**
 *
 * @author Nishan Sameera
 */
public class Tank extends javax.swing.JFrame implements Defenceobserver{
    
   private int lastDefenceLevel = 0;
   private Defenceobservable defenceobservable;
   

    /**
     * Creates new form Tank
     */
    public Tank(Defenceobservable defenceobservable) {
        initComponents();
        this.defenceobservable = defenceobservable;
        btn_shoot.setEnabled(false);
        btn_missile.setEnabled(false);
        btn_redar.setEnabled(false);
        btn_rotate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_shoot = new javax.swing.JButton();
        btn_missile = new javax.swing.JButton();
        btn_redar = new javax.swing.JButton();
        btn_rotate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tank");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Area Not Cleared");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, -1));

        btn_shoot.setText("Shoot");
        jPanel1.add(btn_shoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 118, -1));

        btn_missile.setText("Missile Opertion");
        jPanel1.add(btn_missile, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 160, -1));

        btn_redar.setText("Redar Operation");
        jPanel1.add(btn_redar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        btn_rotate.setText("Rotate Shooting");
        jPanel1.add(btn_rotate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 160, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 290, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 290, -1));

        jButton5.setText("Send");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 148, -1));

        jCheckBox1.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Position");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defence_system/Rectangle tank.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 360, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        boolean checked = jCheckBox1.isSelected();
        boolean enableShoot = (lastDefenceLevel > 20) && checked;
        btn_shoot.setEnabled(enableShoot);
        
        boolean enablemissile = (lastDefenceLevel > 40) && checked;
        btn_missile.setEnabled(enablemissile);
        
        boolean enablereder = (lastDefenceLevel > 60) && checked;
        btn_redar.setEnabled(enablereder);
        
        boolean enablerotate = (lastDefenceLevel > 80) && checked;
        btn_rotate.setEnabled(enablerotate);
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (!jTextField1.getText().equals("")) {
            defenceobservable.sendunimessage("Tank - " +jTextField1.getText()+"\n");
            jTextField1.setText("");
        }else {
            JOptionPane.showMessageDialog(null, "input Your Message", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_missile;
    private javax.swing.JButton btn_redar;
    private javax.swing.JButton btn_rotate;
    private javax.swing.JButton btn_shoot;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(int defenceLevel, boolean areaclear) {
        if (areaclear) {
            jLabel2.setText("Area Is Cleared");  
        }else {
            jLabel2.setText("Area Is Not Cleared");
        }
       boolean enableShoot = (defenceLevel > 20) && jCheckBox1.isSelected();
       btn_shoot.setEnabled(enableShoot);
       
       boolean enableMissile = (defenceLevel > 40) && jCheckBox1.isSelected();
       btn_missile.setEnabled(enableMissile);
       
       boolean enableReder = (defenceLevel > 60) && jCheckBox1.isSelected();
       btn_redar.setEnabled(enableReder);
       
       boolean enableRotate = (defenceLevel > 60) && jCheckBox1.isSelected();
       btn_rotate.setEnabled(enableRotate);
        
    }

    @Override
    public void reciveMessage(String message) {
      jTextArea1.append(message+"\n");
    }

    @Override
    public void unitMessage(String message) {
       
    }

    @Override
    public void priMessage(String message) {
        if (jCheckBox1.isSelected()) {
            jTextArea1.append(message+"\n");
        }
    }
}
